//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataHarvester.Model.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataHarvesterDBEntities : DbContext
    {
        public DataHarvesterDBEntities()
            : base("name=DataHarvesterDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblEmail> tblEmails { get; set; }
        public virtual DbSet<tblFileUrl> tblFileUrls { get; set; }
        public virtual DbSet<tblHost> tblHosts { get; set; }
        public virtual DbSet<tblIP> tblIPs { get; set; }
        public virtual DbSet<tblLinkedInLink> tblLinkedInLinks { get; set; }
        public virtual DbSet<tblLinkedInProfile> tblLinkedInProfiles { get; set; }
        public virtual DbSet<tblPort> tblPorts { get; set; }
        public virtual DbSet<tblResult> tblResults { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
    }
}
