//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataHarvester.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLinkedInProfile
    {
        public int ID { get; set; }
        public string profile { get; set; }
        public int resultID { get; set; }
    
        public virtual tblResult tblResult { get; set; }
    }
}
